services:
  # Base de Datos Local (Opcional, ahora usaremos Atlas)
  mongodb:
    image: mongo:latest
    container_name: mtm-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: mtm-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # --- CONEXIÓN A LA NUBE (ATLAS) ---
      # IMPORTANTE: Reemplaza TU_PASSWORD_REAL por la contraseña de ssagredo13
      - MONGO_URL=mongodb+srv://ssagredo13:ssagredo13@cluster0.jh8wz8e.mongodb.net/match-to-match?retryWrites=true&w=majority&appName=Cluster0
      - DB_NAME=match_to_match
    # Ya no necesita estrictamente el 'depends_on' de mongodb local porque apunta a la nube

  # Frontend React
  frontend:
    build: ./frontend
    container_name: mtm-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  mongo-data: